### PR TITLE
Fix email migrated users script

### PR DESCRIPTION
**Pull request by abought**
# Purpose
Get email_migrated_users script working: fix configuration options and allow a single user testing mode against staging server. Can now use the `.env` file in `lookit/.env` (no need for a separate file), provided an access token setting is added.

## Single user sample
Log some information, but don't send email:
`python email_migrated_users.py -v 2 -u abought  -c ../.env --dry`

Send the email:
`python email_migrated_users.py -v 2 -u abought  -c ../.env`

# Followup
- Updated "Lookit handoff docs" google doc to cover updated script usage and testing options

### CODE REVIEW

**Comment by abought** [comment]
@kimberscott , would you mind taking a look at this?

I've confirmed that it works for single-user mode and sends a reset request for an account on `staging-experimenter`.

 One caveat is that it doesn't seem to set any new flags to indicate a successful migration. For example, if the script fails partway through a mass email campaign due to a single bad request, we don't want to restart the process (and send duplicate emails that annoy people). We only want to email the ones that still need migrating.

Was this something you and Sam discussed- is there a schema field to indicate "successful migration and reset sent" that I might be missing?

**Comment by kimberscott** [comment]
No, there's no schema field or other solution to deal with tracking which emails were already sent. (I'm fine with just logging the completed ones in a file or something since this is single-use, though.)

Just took a look and this works for me as well, but it's sending an older version of the password reset email that I assume is defined on a COS SendGrid account? We'd like to make sure this is sent from (and in general, we're able to use the suppression groups and templates from) the lookitlab account instead. Password reset on the site still sends the newer version from the lookitlab account.

**Comment by kimberscott** [comment]
Nevermind--as discussed this actually works fine once I have it using the correct .env file. I'll go ahead and send the migration emails after setting up to log which ones have been sent successfully.

**Comment by abought** [comment]
Glad it worked! Let me know if you need help with the migration script at
all. If you see errors we can make improvements to suit your needs.

Otherwise for now I'll keep poking at the audio capture component, and see
about adding that sound check indicator.

**Pull request merged**
